# Generated by Django 5.2.10 on 2026-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('colorful', 'Colorful & Fun'), ('modern', 'Modern'), ('elegant', 'Elegant'), ('minimal', 'Minimal')], default='modern', max_length=50),
        ),
    ]
