# Generated by Django 5.2.10 on 2026-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_page_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('birthday', 'Birthday Invitation')], default='birthday', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='theme',
            field=models.CharField(default='modern', max_length=50),
        ),
    ]
